language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: W+5YDXdZuqIqcXsmARjBbPOFQ/gjoIxhB9kj7Xb4YAtBWJV5nqNQP20wQfRI4ZAMESP1qRtjN+8YQwBJRnr4alou7T8r+2j+0hz37v1bJ8am5KaYrgptFZAU5lmfR2S+ITlGYI32mDWv5HJJQcpfsts3kLwjfxoROKzYFnYGRUVcXq7w8+3DamPWMaz73GIrnY5XQXW0YLfzIsHV8xakNV6MdHmkskeNoaG4GdYUJTvNCMN3SZDPyGzoEm1rvz4RTnzinsX/QQP7VFBoXicj995NVH0DTlmhMNaNrQkmUg5qQDLQivFeuzBXUhuZG/NZOG/JcJjRCWdbfbJK8A2cFNNsji1nTpRYkBwk7TbIm3XgK52NyCMujONhuORvPdovr89zRidTUvVpFRCMjxXbVR1ACJQRvf7tVZC3jjleD1RrOn5WeOUjeaj7k8JT59mo2HgLrCVps/uXIThKVoTIx9DebAywv9M/dcLtgXqRk8dkS9BueZU731Wx1iB5XwtahBE8I/cjCqSKHSgmmfI1VT5LSaMr4qTOZrE111u5cBB2qS+UKtLNetyd4OqdPYQLgb/hluCrzsfkKoiAN9eujwkcQW1rKH7WTL7OXFos5+1XgryZRFYBTG4ZHw4Aadm7L52mSH90SbwlWxA73XQePBZbjPIJIXrxzusByyLkOr0=
  app: obscure-meadow-27211
  on:
    repo: rrcheatham/blogAppAPI
